name: Publicar mi Web

on:
  push:
    branches: ["desplegue-pages"] # Solo cuando subimos a la rama principal

# Permisos necesarios para publicar la web
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir la carpeta del código
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Sube todo el contenido del repositorio

      - name: Publicar en Internet
        uses: actions/deploy-pages@v4